# config/packages/vich_uploader.yaml

vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:    
        Photos:
            uri_prefix: /uploads/photos  # URL for photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'  # Local directory for photos
            namer: Vich\UploaderBundle\Naming\UniqidNamer  # Automatically generate unique names for photos

        FloorPlans:
            uri_prefix: /uploads/floorplans  # URL for floorplans
            upload_destination: '%kernel.project_dir%/public/uploads/floorplans'  # Local directory for floorplans
            namer:  Vich\UploaderBundle\Naming\UniqidNamer  # Automatically generate unique names for floorplans
        Documents:
            uri_prefix: /uploads/documents  # URL for floorplans
            upload_destination: '%kernel.project_dir%/public/uploads/documents'  # Local directory for floorplans
            namer:  Vich\UploaderBundle\Naming\UniqidNamer  # Automatically generate unique names for floorplans
        User:
            uri_prefix: /uploads/profile
            upload_destination: '%kernel.project_dir%/public/uploads/profile'
            namer:  Vich\UploaderBundle\Naming\UniqidNamer